<div id="rev_slider_2_1_wrapper" class="rev_slider_wrapper fullscreen-container" style="background-color:#333333;padding:0px;background-image:url({{ asset('front/monsterat/upload/slider_pattern-1.png') }});background-repeat:repeat;background-size:inherit;background-position:left top;">
    <!-- START REVOLUTION SLIDER 5.2.6 fullscreen mode -->
    <div id="rev_slider_2_1" class="rev_slider fullscreenbanner" style="display:none;" data-version="5.2.6">
        <ul>
            <!-- SLIDE  -->
            <li data-index="rs-9" data-transition="crossfade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="600" data-thumb="{{ asset('front/monsterat/upload/slider_bg4.jpg') }}" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="300" data-fsslotamount="7" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg4.jpg') }}" alt="" title="slider_bg4" width="1600" height="812" data-bgposition="center center" data-kenburns="on" data-duration="10000" data-ease="Linear.easeNone" data-scalestart="100" data-scaleend="110" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 0" data-offsetend="0 0" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-9-layer-6" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-90','-90','-200','-140']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="opacity:0;s:300;" data-start="700" data-responsive_offset="on" style="z-index: 5;"><img src="{{ asset('front/monsterat/upload/slider_icon1.png') }}" alt="" width="112" height="112" data-ww="['112px','112px','112px','112px']" data-hh="['112px','112px','112px','112px']" data-no-retina> </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-9-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['20','20','-40','-10']" data-fontsize="['64','54','64','48']" data-lineheight="['74','74','74','58']" data-width="['1035','1035','638','470']" data-height="['none','none','none','117']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="800" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 1035px; max-width: 1035px; white-space: normal; font-size: 64px; line-height: 74px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;">HELLO! WE ARE MONTSERRAT </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-9-layer-2" data-x="['center','center','center','center']" data-hoffset="['2','2','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['90','90','80','90']" data-fontsize="['22','20','22','14']" data-lineheight="['32','32','32','24']" data-width="['1171','1171','712','435']" data-height="['none','none','none','74']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; min-width: 1171px; max-width: 1171px; white-space: normal; font-size: 22px; line-height: 32px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;text-transform:uppercase;letter-spacing:4px;">We Create Awesome and Powerful Websites For Business! </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-9-layer-4" data-x="['left','center','center','left']" data-hoffset="['363','-110','-120','-1']" data-y="['top','top','top','top']" data-voffset="['463','470','470','328']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(51, 51, 51, 1.00);bg:rgba(255, 255, 255, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(240, 99, 76, 1.00);padding:15px 45px 15px 45px;border-color:rgba(0, 0, 0, 1.00);outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Purchase now </div>

                <!-- LAYER NR. 5 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-9-layer-5" data-x="['left','center','center','right']" data-hoffset="['593','120','110','-1']" data-y="['top','top','middle','bottom']" data-voffset="['463','470','167','28']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(51, 51, 51, 1.00);bg:rgba(255, 255, 255, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power2.easeOut;" data-start="1100" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 9; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;padding:13px 45px 13px 45px;border-color:rgba(255, 255, 255, 1.00);border-style:solid;border-width:2px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Discover more </div>
            </li>
            <!-- SLIDE  -->
            <li data-index="rs-8" data-transition="crossfade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="600" data-thumb="{{ asset('front/monsterat/upload/slider_bg5.jpg') }}" data-rotate="0" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg5.jpg') }}" alt="" title="slider_bg5" width="1600" height="812" data-bgposition="center center" data-kenburns="on" data-duration="10000" data-ease="Linear.easeNone" data-scalestart="100" data-scaleend="110" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 0" data-offsetend="0 0" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-8-layer-6" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-90','-90','-200','-140']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="opacity:0;s:300;" data-start="700" data-responsive_offset="on" style="z-index: 5;"><img src="{{ asset('front/monsterat/upload/slider_icon2.png') }}" alt="" width="112" height="112" data-ww="['112px','112px','112px','112px']" data-hh="['112px','112px','112px','112px']" data-no-retina> </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-8-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['20','20','-40','-10']" data-fontsize="['64','54','64','48']" data-lineheight="['74','64','74','58']" data-width="['1035','1035','720','440']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:600;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="800" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 1035px; max-width: 1035px; white-space: normal; font-size: 64px; line-height: 74px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;">BRILLIANT CODE QUALITY </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-8-layer-2" data-x="['center','center','center','center']" data-hoffset="['2','2','2','2']" data-y="['middle','middle','middle','middle']" data-voffset="['90','90','80','90']" data-fontsize="['22','20','20','14']" data-lineheight="['32','30','30','24']" data-width="['1171','1171','598','440']" data-height="['none','none','61','61']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; min-width: 1171px; max-width: 1171px; white-space: normal; font-size: 22px; line-height: 32px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;text-transform:uppercase;letter-spacing:4px;">We Create Awesome and Powerful Websites For Business! </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-8-layer-4" data-x="['left','left','center','center']" data-hoffset="['363','258','-120','-114']" data-y="['top','top','top','top']" data-voffset="['463','463','463','328']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(51, 51, 51, 1.00);bg:rgba(255, 255, 255, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(240, 99, 76, 1.00);padding:15px 45px 15px 45px;border-color:rgba(0, 0, 0, 1.00);outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Purchase now </div>

                <!-- LAYER NR. 5 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-8-layer-5" data-x="['left','left','center','center']" data-hoffset="['593','488','110','112']" data-y="['top','top','top','top']" data-voffset="['463','463','463','328']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(51, 51, 51, 1.00);bg:rgba(255, 255, 255, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power2.easeOut;" data-start="1100" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 9; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;padding:13px 45px 13px 45px;border-color:rgba(255, 255, 255, 1.00);border-style:solid;border-width:2px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Discover more </div>
            </li>
            <!-- SLIDE  -->
            <li data-index="rs-10" data-transition="crossfade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="600" data-thumb="{{ asset('front/monsterat/upload/slider_bg6.jpg') }}" data-rotate="0" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg6.jpg') }}" alt="" title="slider_bg6" width="1600" height="812" data-bgposition="center center" data-kenburns="on" data-duration="10000" data-ease="Linear.easeNone" data-scalestart="100" data-scaleend="110" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 0" data-offsetend="0 0" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-10-layer-6" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-90','-90','-200','-140']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="opacity:0;s:300;" data-start="700" data-responsive_offset="on" style="z-index: 5;"><img src="{{ asset('front/monsterat/upload/slider_icon3.png') }}" alt="" width="112" height="112" data-ww="['112px','112px','112px','112px']" data-hh="['112px','112px','112px','112px']" data-no-retina> </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-10-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['20','20','-40','-10']" data-fontsize="['64','54','64','48']" data-lineheight="['74','64','74','58']" data-width="['1035','1035','544','440']" data-height="['none','none','149','117']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-mask_in="x:0px;y:[100%];" data-start="800" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 1035px; max-width: 1035px; white-space: normal; font-size: 64px; line-height: 74px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;">SMART DESIGN & MEDIA </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-10-layer-2" data-x="['center','center','center','center']" data-hoffset="['2','2','2','2']" data-y="['middle','middle','middle','middle']" data-voffset="['90','90','80','80']" data-fontsize="['22','20','22','14']" data-lineheight="['32','30','30','24']" data-width="['1171','1171','720','440']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-mask_in="x:0px;y:[100%];" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; min-width: 1171px; max-width: 1171px; white-space: normal; font-size: 22px; line-height: 32px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;text-transform:uppercase;letter-spacing:4px;">We Create Awesome and Powerful Websites For Business! </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-10-layer-4" data-x="['left','center','center','center']" data-hoffset="['363','-110','-110','-114']" data-y="['top','top','top','top']" data-voffset="['463','463','463','328']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(51, 51, 51, 1.00);bg:rgba(255, 255, 255, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(240, 99, 76, 1.00);padding:15px 45px 15px 45px;border-color:rgba(0, 0, 0, 1.00);outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Purchase now </div>

                <!-- LAYER NR. 5 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-10-layer-5" data-x="['left','center','center','center']" data-hoffset="['593','120','120','112']" data-y="['top','top','top','top']" data-voffset="['463','463','463','328']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(51, 51, 51, 1.00);bg:rgba(255, 255, 255, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:600;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power2.easeOut;" data-start="1100" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 9; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;padding:13px 45px 13px 45px;border-color:rgba(255, 255, 255, 1.00);border-style:solid;border-width:2px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Discover more </div>
            </li>
        </ul>

        <div class="tp-bannertimer" style="height: 5px; background-color: rgba(255, 255, 255, 0.15);"></div>
    </div>

</div>
