<div id="rev_slider_1_1_wrapper" class="rev_slider_wrapper fullscreen-container" style="background-color:#333333;padding:0px;background-image:url({{ asset('front/monsterat/upload/slider_pattern-1.png') }});background-repeat:repeat;background-size:inherit;background-position:left top;">
    <!-- START REVOLUTION SLIDER 5.2.6 fullscreen mode -->
    <div id="rev_slider_1_1" class="rev_slider fullscreenbanner" style="display:none;" data-version="5.2.6">
        <ul>
            <!-- SLIDE  -->
            <li data-index="rs-4" data-transition="slideleft" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="{{ asset('front/monsterat/upload/slider_bg1-1.jpg') }}" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="300" data-fsslotamount="7" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg1-1.jpg') }}" alt="" title="slider_bg1" width="1920" height="1080" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-4-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-20','-20','-20','-80']" data-fontsize="['72','72','60','36']" data-lineheight="['84','84','70','46']" data-width="['1170','1170','778','480']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; min-width: 1170px; max-width: 1170px; white-space: normal; font-size: 72px; line-height: 84px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;">WE ARE MONTSERRAT CREATIVE AGENCY </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-4-layer-2" data-x="['center','center','center','center']" data-hoffset="['2','2','2','2']" data-y="['middle','middle','middle','middle']" data-voffset="['90','90','80','4']" data-width="['918','918','918','402']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1050" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 918px; max-width: 918px; white-space: normal; font-size: 24px; line-height: 34px; font-weight: 300; color: rgba(255, 255, 255, 1.00);font-family:Open Sans;text-align:center;">We Create Awesome and Powerful Websites For Business! </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-4-layer-4" data-x="['left','center','center','center']" data-hoffset="['362','-117','-117','-114']" data-y="['top','top','top','top']" data-voffset="['463','463','453','257']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1200" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(240, 99, 76, 1.00);padding:15px 45px 15px 45px;border-color:rgba(0, 0, 0, 1.00);outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Purchase now </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-4-layer-5" data-x="['left','center','center','center']" data-hoffset="['593','117','117','114']" data-y="['top','top','top','top']" data-voffset="['463','463','453','257']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power2.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power2.easeOut;" data-start="1350" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(51, 51, 51, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(255, 255, 255, 1.00);padding:15px 45px 15px 45px;border-color:rgba(0, 0, 0, 1.00);outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Discover more </div>
            </li>
            <!-- SLIDE  -->
            <li data-index="rs-1" data-transition="slideleft" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="{{ asset('front/monsterat/upload/slider_bg2-1.jpg') }}" data-rotate="0" data-saveperformance="off" data-title="Slide 2" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg2-1.jpg') }}" alt="" title="slider_bg2" width="1920" height="1080" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-1-layer-1" data-x="['right','right','center','center']" data-hoffset="['-3','-3','16','-22']" data-y="['middle','middle','middle','middle']" data-voffset="['-40','-40','-40','-80']" data-fontsize="['72','72','60','36']" data-lineheight="['82','82','70','46']" data-width="['951','951','688','481']" data-height="['165','165','167','none']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; min-width: 951px; max-width: 951px; max-width: 165px; max-width: 165px; white-space: normal; font-size: 72px; line-height: 82px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:right;">CREATIVE STUDIO DESIGN WORLDWIDE </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-1-layer-2" data-x="['center','center','center','center']" data-hoffset="['235','132','10','15']" data-y="['middle','middle','middle','middle']" data-voffset="['80','80','50','10']" data-width="['700','700','700','402']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1050" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 700px; max-width: 700px; white-space: normal; font-size: 24px; line-height: 34px; font-weight: 300; color: rgba(255, 255, 255, 1.00);font-family:Open Sans;text-align:right;">We Create Awesome and Powerful Websites For Business! </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-1-layer-4" data-x="['left','left','center','center']" data-hoffset="['725','515','20','-114']" data-y="['top','top','middle','middle']" data-voffset="['461','461','120','90']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1200" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(240, 99, 76, 1.00);padding:15px 45px 15px 45px;border-color:rgba(0, 0, 0, 1.00);outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Purchase now </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-1-layer-5" data-x="['left','left','center','center']" data-hoffset="['956','746','254','114']" data-y="['top','top','middle','middle']" data-voffset="['461','461','120','90']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1350" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(51, 51, 51, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(255, 255, 255, 1.00);padding:15px 45px 15px 45px;border-color:rgba(0, 0, 0, 1.00);outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Discover more </div>
            </li>
            <!-- SLIDE  -->
            <li data-index="rs-5" data-transition="slideleft" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="{{ asset('front/monsterat/upload/slider_bg3-1.jpg') }}" data-rotate="0" data-saveperformance="off" data-title="Slide 3" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg3-1.jpg') }}" alt="" title="slider_bg3" width="1920" height="1080" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-5-layer-1" data-x="['left','left','left','left']" data-hoffset="['-3','-3','-3','-3']" data-y="['middle','middle','middle','middle']" data-voffset="['-30','-30','-30','-80']" data-fontsize="['72','72','60','36']" data-lineheight="['82','82','70','46']" data-width="['938','938','720','441']" data-height="['165','165','165','none']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; min-width: 938px; max-width: 938px; max-width: 165px; max-width: 165px; white-space: normal; font-size: 72px; line-height: 82px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;">CREATIVE STUDIO DESIGN WORLDWIDE </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-5-layer-2" data-x="['center','center','center','center']" data-hoffset="['-234','-129','-9','0']" data-y="['middle','middle','middle','middle']" data-voffset="['81','81','61','11']" data-width="['700','700','700','439']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1050" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 700px; max-width: 700px; white-space: normal; font-size: 24px; line-height: 34px; font-weight: 300; color: rgba(255, 255, 255, 1.00);font-family:Open Sans;">We Create Awesome and Powerful Websites For Business! </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-5-layer-4" data-x="['left','left','left','left']" data-hoffset="['-1','-1','-1','-1']" data-y="['top','top','top','top']" data-voffset="['463','463','433','270']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1200" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(240, 99, 76, 1.00);padding:15px 45px 15px 45px;border-color:rgba(0, 0, 0, 1.00);outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Purchase now </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-5-layer-5" data-x="['left','left','left','left']" data-hoffset="['232','232','232','227']" data-y="['top','top','top','top']" data-voffset="['463','463','434','270']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1350" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(51, 51, 51, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(255, 255, 255, 1.00);padding:15px 45px 15px 45px;border-color:rgba(0, 0, 0, 1.00);outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Discover more </div>
            </li>
        </ul>

        <div class="tp-bannertimer" style="height: 5px; background-color: rgba(255, 255, 255, 0.15);"></div>
    </div>

</div>

