<div id="rev_slider_3_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto;background-color:#333333;padding:0px;margin-top:0px;margin-bottom:0px;background-image:url({{ asset('front/monsterat/upload/slider_pattern-1.png') }});background-repeat:repeat;background-size:inherit;background-position:left top;">
    <!-- START REVOLUTION SLIDER 5.2.6 auto mode -->
    <div id="rev_slider_3_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.2.6">
        <ul>
            <!-- SLIDE  -->
            <li data-index="rs-12" data-transition="crossfade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="600" data-thumb="{{ asset('front/monsterat/upload/slider_bg7.jpg') }}" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="300" data-fsslotamount="7" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg7.jpg') }}" alt="" title="slider_bg7" width="1600" height="812" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-12-layer-6" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['0','0','0','0']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="700" data-responsive_offset="on" style="z-index: 5;"><img src="{{ asset('front/monsterat/upload/monitors_all.png') }}" alt="" width="1085" height="409" data-ww="['1085px','900px','680px','400']" data-hh="['409px','339px','256px','151']" data-no-retina> </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-12-layer-1" data-x="['center','center','center','center']" data-hoffset="['2','2','4','4']" data-y="['middle','middle','middle','middle']" data-voffset="['-150','-170','-121','-81']" data-fontsize="['64','64','64','34']" data-width="1035" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 1035px; max-width: 1035px; white-space: normal; font-size: 64px; line-height: 74px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;">WELCOME ABROAD </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-12-layer-2" data-x="['center','center','center','center']" data-hoffset="['2','2','2','2']" data-y="['middle','middle','middle','middle']" data-voffset="['-90','-110','-60','-10']" data-fontsize="['20','20','14','14']" data-lineheight="['30','30','30','24']" data-width="['1171','1171','721','440']" data-height="['none','none','none','61']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1200" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; min-width: 1171px; max-width: 1171px; white-space: normal; font-size: 20px; line-height: 30px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;text-transform:uppercase;letter-spacing:4px;">We Create Awesome and Powerful Websites For Business! </div>
            </li>
            <!-- SLIDE  -->
            <li data-index="rs-13" data-transition="crossfade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="600" data-thumb="{{ asset('front/monsterat/upload/slider_bg8.jpg') }}" data-rotate="0" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg8.jpg') }}" alt="" title="slider_bg8" width="1600" height="812" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-13-layer-6" data-x="['right','right','right','right']" data-hoffset="['10','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['100','50','50','50']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="700" data-responsive_offset="on" style="z-index: 5;"><img src="{{ asset('front/monsterat/upload/tablet.png') }}" alt="" width="446" height="643" data-ww="['446px','350px','350px','350px']" data-hh="['643px','505','505px','505px']" data-no-retina> </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-13-layer-2" data-x="['left','left','left','left']" data-hoffset="['10','0','0','20']" data-y="['middle','middle','middle','middle']" data-voffset="['-90','-60','-120','-80']" data-fontsize="['22','22','22','14']" data-lineheight="['32','32','32','24']" data-width="547" data-height="33" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="800" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 547px; max-width: 547px; max-width: 33px; max-width: 33px; white-space: normal; font-size: 22px; line-height: 32px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;letter-spacing:4px;">We Create Powerful Websites! </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-13-layer-1" data-x="['left','left','left','left']" data-hoffset="['10','0','0','20']" data-y="['middle','middle','middle','middle']" data-voffset="['15','65','-5','-15']" data-fontsize="['64','64','64','34']" data-lineheight="['74','74','74','44']" data-width="['579','579','579','339']" data-height="['150','150','150','89']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; min-width: 579px; max-width: 579px; max-width: 150px; max-width: 150px; white-space: normal; font-size: 64px; line-height: 74px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;">SIMPLE & SMART HUGE WEBSITES </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-13-layer-4" data-x="['left','left','left','left']" data-hoffset="['10','0','0','20']" data-y="['top','top','top','top']" data-voffset="['533','473','354','254']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1100" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(240, 99, 76, 1.00);padding:15px 45px 15px 45px;border-color:rgba(0, 0, 0, 1.00);outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Purchase now </div>

                <!-- LAYER NR. 5 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-13-layer-5" data-x="['left','left','left','left']" data-hoffset="['263','263','263','17']" data-y="['top','top','top','top']" data-voffset="['533','474','354','274']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','on','off']" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power2.easeOut;" data-start="1200" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 9; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;padding:13px 45px 13px 45px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Watch vide now </div>

                <!-- LAYER NR. 6 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-13-layer-7" data-x="['left','left','left','left']" data-hoffset="['249','249','249','-1']" data-y="['top','top','top','top']" data-voffset="['531','472','352','272']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','on','off']" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;" data-start="1200" data-responsive_offset="on" style="z-index: 10;"><img src="{{ asset('front/monsterat/upload/slider_play_icon.png') }}" alt="" width="46" height="46" data-ww="['46px','46px','46px','46px']" data-hh="['46px','46px','46px','46px']" data-no-retina> </div>
            </li>
            <!-- SLIDE  -->
            <li data-index="rs-14" data-transition="crossfade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="600" data-thumb="{{ asset('front/monsterat/upload/slider_bg10.jpg') }}" data-rotate="0" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg10.jpg') }}" alt="" title="slider_bg10" width="1600" height="811" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-14-layer-6" data-x="['left','left','left','left']" data-hoffset="['10','0','0','0']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['-20','-20','-20','-20']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="700" data-responsive_offset="on" style="z-index: 5;"><img src="{{ asset('front/monsterat/upload/phone_slider.png') }}" alt="" width="494" height="689" data-ww="['494px','350','350px','350px']" data-hh="['689px','488','488px','488px']" data-no-retina> </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-14-layer-2" data-x="['right','right','right','left']" data-hoffset="['40','40','171','20']" data-y="['middle','middle','middle','middle']" data-voffset="['-90','-90','-120','-70']" data-fontsize="['22','22','22','14']" data-lineheight="['32','32','32','24']" data-width="['547','547','547','440']" data-height="33" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 547px; max-width: 547px; max-width: 33px; max-width: 33px; white-space: normal; font-size: 22px; line-height: 32px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;letter-spacing:4px;">We Create Powerful Websites! </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-14-layer-1" data-x="['right','right','right','center']" data-hoffset="['10','10','139','20']" data-y="['middle','middle','middle','middle']" data-voffset="['15','15','-15','-5']" data-fontsize="['64','64','64','34']" data-lineheight="['74','74','74','44']" data-width="['579','579','579','441']" data-height="['150','150','150','none']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; min-width: 579px; max-width: 579px; max-width: 150px; max-width: 150px; white-space: normal; font-size: 64px; line-height: 74px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;">SIMPLE & SMART HUGE WEBSITES </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-14-layer-4" data-x="['right','right','right','left']" data-hoffset="['370','372','508','20']" data-y="['top','top','top','top']" data-voffset="['533','413','333','261']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1100" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(240, 99, 76, 1.00);padding:15px 45px 15px 45px;border-color:rgba(0, 0, 0, 1.00);outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Purchase now </div>

                <!-- LAYER NR. 5 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-14-layer-5" data-x="['left','left','left','left']" data-hoffset="['824','604','234','50']" data-y="['top','top','top','top']" data-voffset="['533','412','333','285']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','on','off']" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);bc:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1200" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 9; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(51, 51, 51, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(255, 255, 255, 1.00);padding:13px 45px 13px 45px;border-color:rgba(255, 255, 255, 1.00);border-style:solid;border-width:2px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Watch vide now </div>
            </li>
            <!-- SLIDE  -->
            <li data-index="rs-11" data-transition="crossfade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="600" data-thumb="{{ asset('front/monsterat/upload/slider_bg9.jpg') }}" data-rotate="0" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg9.jpg') }}" alt="" title="slider_bg9" width="1600" height="811" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-11-layer-2" data-x="['center','center','center','center']" data-hoffset="['4','4','4','4']" data-y="['middle','middle','middle','middle']" data-voffset="['-41','-41','-71','-71']" data-fontsize="['22','22','22','14']" data-width="['572','572','572','440']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; min-width: 572px; max-width: 572px; white-space: normal; font-size: 22px; line-height: 32px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;text-transform:uppercase;letter-spacing:4px;">We Create Powerful Websites! </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-11-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['30','30','30','10']" data-fontsize="['64','64','64','44']" data-lineheight="['74','74','74','54']" data-width="['1035','1035','720','440']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 1035px; max-width: 1035px; white-space: normal; font-size: 64px; line-height: 74px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;">START YOUR WEBSITE NOW </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-11-layer-4" data-x="['left','center','center','center']" data-hoffset="['363','-117','-117','-117']" data-y="['top','middle','middle','middle']" data-voffset="['493','110','150','110']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1200" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(240, 99, 76, 1.00);padding:15px 45px 15px 45px;border-color:rgba(0, 0, 0, 1.00);outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Purchase now </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-11-layer-5" data-x="['left','center','center','center']" data-hoffset="['593','117','117','117']" data-y="['top','middle','middle','middle']" data-voffset="['493','110','150','110']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);bc:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:500;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(51, 51, 51, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(255, 255, 255, 1.00);padding:13px 45px 13px 45px;border-color:rgba(255, 255, 255, 1.00);border-style:solid;border-width:2px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Discover more </div>
            </li>
        </ul>

        <div class="tp-bannertimer" style="height: 5px; background-color: rgba(255, 255, 255, 0.15);"></div>
    </div>

</div>
