<div id="rev_slider_4_1_wrapper" class="rev_slider_wrapper fullscreen-container" style="background-color:#f5f5f5;padding:0px;">
    <!-- START REVOLUTION SLIDER 5.2.6 fullscreen mode -->
    <div id="rev_slider_4_1" class="rev_slider fullscreenbanner" style="display:none;" data-version="5.2.6">
        <ul>
            <!-- SLIDE  -->
            <li data-index="rs-17" data-transition="slideremoveleft" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="{{ asset('front/monsterat/upload/slider_bg11.jpg') }}" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="300" data-fsslotamount="7" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg11.jpg') }}" alt="" title="slider_bg11" width="1600" height="812" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-17-layer-6" data-x="['left','left','left','left']" data-hoffset="['10','10','10','10']" data-y="['middle','middle','middle','middle']" data-voffset="['-85','-85','-85','-85']" data-fontsize="['76','76','76','56']" data-width="295" data-height="77" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="700" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; min-width: 295px; max-width: 295px; max-width: 77px; max-width: 77px; white-space: normal; font-size: 76px; line-height: 74px; font-weight: 700; color: rgba(240, 99, 76, 1.00);font-family:Montserrat;">HELLO! </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-17-layer-1" data-x="['left','left','left','left']" data-hoffset="['310','310','310','230']" data-y="['middle','middle','middle','middle']" data-voffset="['-85','-85','-85','-85']" data-fontsize="['76','76','76','56']" data-width="253" data-height="76" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="700" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 253px; max-width: 253px; max-width: 76px; max-width: 76px; white-space: normal; font-size: 76px; line-height: 74px; font-weight: 700; color: rgba(51, 51, 51, 1.00);font-family:Montserrat;">I AM </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-17-layer-7" data-x="['left','left','left','left']" data-hoffset="['10','10','10','10']" data-y="['middle','middle','middle','middle']" data-voffset="['30','30','30','10']" data-fontsize="['76','76','76','40']" data-width="691" data-height="149" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="700" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; min-width: 691px; max-width: 691px; max-width: 149px; max-width: 149px; white-space: normal; font-size: 76px; line-height: 74px; font-weight: 700; color: rgba(51, 51, 51, 1.00);font-family:Montserrat;">SANDRA MCDOE </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-17-layer-2" data-x="['left','left','left','left']" data-hoffset="['10','10','10','10']" data-y="['middle','middle','middle','middle']" data-voffset="['60','60','60','30']" data-width="['700','700','700','430']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="800" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; min-width: 700px; max-width: 700px; white-space: normal; font-size: 24px; line-height: 34px; font-weight: 300; color: rgba(153, 153, 153, 1.00);font-family:Open Sans;">We Create Awesome and Powerful Websites For Business! </div>

                <!-- LAYER NR. 5 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-17-layer-4" data-x="['left','left','left','left']" data-hoffset="['10','10','10','10']" data-y="['top','top','top','top']" data-voffset="['433','433','433','280']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(240, 99, 76, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 9; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(119, 119, 119, 1.00);font-family:Montserrat;text-transform:uppercase;padding:15px 45px 15px 45px;border-color:rgba(240, 99, 76, 1.00);border-style:solid;border-width:3px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">DISCOVER BIOGRAPHY </div>
            </li>
            <!-- SLIDE  -->
            <li data-index="rs-18" data-transition="slideoverleft" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="{{ asset('front/monsterat/upload/slider_bg12.jpg') }}" data-rotate="0" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg12.jpg') }}" alt="" title="slider_bg12" width="1600" height="812" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-18-layer-6" data-x="['right','right','right','right']" data-hoffset="['10','10','10','10']" data-y="['middle','middle','middle','middle']" data-voffset="['-85','-85','-85','-85']" data-fontsize="['76','76','76','57']" data-width="563" data-height="77" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="700" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; min-width: 563px; max-width: 563px; max-width: 77px; max-width: 77px; white-space: normal; font-size: 76px; line-height: 74px; font-weight: 700; color: rgba(240, 99, 76, 1.00);font-family:Montserrat;text-align:right;">DISCOVER </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-18-layer-7" data-x="['right','right','right','right']" data-hoffset="['10','10','10','10']" data-y="['middle','middle','middle','middle']" data-voffset="['30','30','30','11']" data-fontsize="['76','76','76','35']" data-width="725" data-height="149" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="700" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 725px; max-width: 725px; max-width: 149px; max-width: 149px; white-space: normal; font-size: 76px; line-height: 74px; font-weight: 700; color: rgba(51, 51, 51, 1.00);font-family:Montserrat;text-align:right;">MY BEST WORKS </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-18-layer-2" data-x="['right','right','right','right']" data-hoffset="['10','10','10','10']" data-y="['middle','middle','middle','middle']" data-voffset="['60','60','60','30']" data-width="['700','700','700','430']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="800" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; min-width: 700px; max-width: 700px; white-space: normal; font-size: 24px; line-height: 34px; font-weight: 300; color: rgba(153, 153, 153, 1.00);font-family:Open Sans;text-align:right;">We Create Awesome and Powerful Websites For Business! </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-18-layer-4" data-x="['right','right','right','right']" data-hoffset="['10','10','10','10']" data-y="['top','top','top','top']" data-voffset="['433','433','433','280']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(240, 99, 76, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(119, 119, 119, 1.00);font-family:Montserrat;text-transform:uppercase;padding:15px 45px 15px 45px;border-color:rgba(240, 99, 76, 1.00);border-style:solid;border-width:3px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">DISCOVER PORTFOLIO </div>
            </li>
            <!-- SLIDE  -->
            <li data-index="rs-19" data-transition="slideoverleft" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="{{ asset('front/monsterat/upload/slider_bg13.jpg') }}" data-rotate="0" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg13.jpg') }}" alt="" title="slider_bg13" width="1600" height="812" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-19-layer-6" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-95','-95','-95','-95']" data-fontsize="['76','76','76','56']" data-width="563" data-height="77" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="700" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; min-width: 563px; max-width: 563px; max-width: 77px; max-width: 77px; white-space: normal; font-size: 76px; line-height: 74px; font-weight: 700; color: rgba(240, 99, 76, 1.00);font-family:Montserrat;text-align:center;">START TODAY </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-19-layer-7" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-10','-10','-30','-40']" data-fontsize="['76','66','46','27']" data-width="1170" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="800" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 1170px; max-width: 1170px; white-space: normal; font-size: 76px; line-height: 74px; font-weight: 700; color: rgba(51, 51, 51, 1.00);font-family:Montserrat;text-align:center;">I AM FREE FOR FREELANCE </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-19-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['60','60','20','20']" data-width="['700','700','700','440']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; min-width: 700px; max-width: 700px; white-space: normal; font-size: 24px; line-height: 34px; font-weight: 300; color: rgba(153, 153, 153, 1.00);font-family:Open Sans;text-align:center;">We Create Awesome and Powerful Websites For Business! </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-19-layer-4" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['433','433','383','273']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(240, 99, 76, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(119, 119, 119, 1.00);font-family:Montserrat;text-align:center;text-transform:uppercase;padding:15px 45px 15px 45px;border-color:rgba(240, 99, 76, 1.00);border-style:solid;border-width:3px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">DISCOVER PORTFOLIO </div>
            </li>
        </ul>

        <div class="tp-bannertimer" style="height: 5px; background-color: rgba(255, 255, 255, 0.15);"></div>
    </div>

</div>
