<div id="rev_slider_5_1_wrapper" class="rev_slider_wrapper fullscreen-container" style="background-color:#f5f5f5;padding:0px;">
    <!-- START REVOLUTION SLIDER 5.2.6 fullscreen mode -->
    <div id="rev_slider_5_1" class="rev_slider fullscreenbanner" style="display:none;" data-version="5.2.6">
        <ul>
            <!-- SLIDE  -->
            <li data-index="rs-22" data-transition="crossfade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="{{ asset('front/monsterat/upload/slider_bg_shop1.jpg') }}" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="300" data-fsslotamount="7" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg_shop1.jpg') }}" alt="" title="slider_bg_shop1" width="1600" height="812" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-22-layer-6" data-x="['left','left','left','left']" data-hoffset="['10','10','10','10']" data-y="['middle','middle','middle','middle']" data-voffset="['-85','-85','-85','-115']" data-fontsize="['64','64','64','34']" data-lineheight="['74','74','74','50']" data-width="['530','530','530','300']" data-height="['77','77','77','50']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="700" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; min-width: 530px; max-width: 530px; max-width: 77px; max-width: 77px; white-space: normal; font-size: 64px; line-height: 74px; font-weight: 700; color: rgba(68, 68, 68, 1.00);font-family:Montserrat;text-align:center;background-color:rgba(255, 255, 255, 1.00);">SUMMER SALE! </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-22-layer-7" data-x="['left','left','left','left']" data-hoffset="['10','10','10','10']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','-60']" data-fontsize="['64','64','64','34']" data-lineheight="['74','74','74','50']" data-width="['562','562','562','300']" data-height="['76','76','76','50']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="800" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 562px; max-width: 562px; max-width: 76px; max-width: 76px; white-space: normal; font-size: 64px; line-height: 74px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;background-color:rgba(240, 99, 76, 1.00);">SAVE UPTO 70% </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-22-layer-2" data-x="['left','left','left','left']" data-hoffset="['11','11','11','10']" data-y="['middle','middle','middle','middle']" data-voffset="['78','78','78','8']" data-width="['631','631','631','441']" data-height="['31','31','31','69']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; min-width: 631px; max-width: 631px; max-width: 31px; max-width: 31px; white-space: normal; font-size: 20px; line-height: 30px; font-weight: 300; color: rgba(153, 153, 153, 1.00);font-family:Open Sans;text-transform:uppercase;">We Create Awesome and Powerful Websites For Business! </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-22-layer-4" data-x="['left','left','left','left']" data-hoffset="['10','10','10','10']" data-y="['top','top','top','top']" data-voffset="['443','443','443','250']" data-width="['none','none','none','219']" data-height="['none','none','none','53']" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);bc:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(146, 146, 146, 1.00);padding:15px 45px 15px 45px;border-color:rgba(146, 146, 146, 1.00);border-style:solid;border-width:3px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">SHOPPING NOW </div>

                <!-- LAYER NR. 5 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-22-layer-8" data-x="['left','left','left','left']" data-hoffset="['245','245','245','10']" data-y="['top','top','top','top']" data-voffset="['443','443','443','310']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(240, 99, 76, 1.00);bc:rgba(240, 99, 76, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1100" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 9; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(119, 119, 119, 1.00);font-family:Montserrat;text-transform:uppercase;padding:15px 45px 15px 45px;border-color:rgba(146, 146, 146, 1.00);border-style:solid;border-width:3px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">DISCOVER MORE </div>
            </li>
            <!-- SLIDE  -->
            <li data-index="rs-23" data-transition="crossfade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="{{ asset('front/monsterat/upload/slider_bg_shop2.jpg') }}" data-rotate="0" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg_shop2.jpg') }}" alt="" title="slider_bg_shop2" width="1600" height="812" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-23-layer-6" data-x="['right','right','right','left']" data-hoffset="['11','81','81','10']" data-y="['middle','middle','middle','middle']" data-voffset="['-85','-85','-85','-105']" data-fontsize="['64','64','64','34']" data-lineheight="['74','74','74','50']" data-width="['530','530','530','300']" data-height="['77','77','77','50']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="700" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; min-width: 530px; max-width: 530px; max-width: 77px; max-width: 77px; white-space: normal; font-size: 64px; line-height: 74px; font-weight: 700; color: rgba(68, 68, 68, 1.00);font-family:Montserrat;text-align:center;background-color:rgba(255, 255, 255, 1.00);">SUMMER SALE! </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-23-layer-7" data-x="['right','right','right','left']" data-hoffset="['-20','50','50','10']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','-50']" data-fontsize="['64','64','64','34']" data-lineheight="['74','74','74','50']" data-width="['562','562','562','300']" data-height="['76','76','76','50']" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="800" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 562px; max-width: 562px; max-width: 76px; max-width: 76px; white-space: normal; font-size: 64px; line-height: 74px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;background-color:rgba(240, 99, 76, 1.00);">SAVE UPTO 70% </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-23-layer-2" data-x="['right','right','right','left']" data-hoffset="['-90','-20','-20','10']" data-y="['middle','middle','middle','middle']" data-voffset="['76','76','76','6']" data-width="['631','631','631','440']" data-height="31" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; min-width: 631px; max-width: 631px; max-width: 31px; max-width: 31px; white-space: normal; font-size: 20px; line-height: 30px; font-weight: 300; color: rgba(153, 153, 153, 1.00);font-family:Open Sans;text-transform:uppercase;">We Create Awesome and Powerful Websites For Business! </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-23-layer-4" data-x="['right','right','right','left']" data-hoffset="['326','396','396','10']" data-y="['top','top','top','top']" data-voffset="['443','443','443','260']" data-width="['none','none','none','219']" data-height="['none','none','none','51']" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);bc:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-transform:uppercase;background-color:rgba(146, 146, 146, 1.00);padding:15px 45px 15px 45px;border-color:rgba(146, 146, 146, 1.00);border-style:solid;border-width:3px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">SHOPPING NOW </div>

                <!-- LAYER NR. 5 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-23-layer-8" data-x="['right','right','right','left']" data-hoffset="['86','156','156','10']" data-y="['top','top','top','top']" data-voffset="['442','442','442','320']" data-width="['none','none','none','221']" data-height="['none','none','none','52']" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(240, 99, 76, 1.00);bc:rgba(240, 99, 76, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="1100" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 9; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(119, 119, 119, 1.00);font-family:Montserrat;text-transform:uppercase;padding:15px 45px 15px 45px;border-color:rgba(146, 146, 146, 1.00);border-style:solid;border-width:3px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">DISCOVER MORE </div>
            </li>
            <!-- SLIDE  -->
            <li data-index="rs-24" data-transition="crossfade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="{{ asset('front/monsterat/upload/slider_bg14.jpg') }}" data-rotate="0" data-saveperformance="off" data-title="Slide 1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                <img src="{{ asset('front/monsterat/upload/slider_bg14.jpg') }}" alt="" title="slider_bg14" width="1600" height="811" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>
                <!-- LAYERS -->

                <!-- LAYER NR. 1 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-24-layer-7" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-fontsize="['64','54','34','24']" data-width="['980','900','530','390']" data-height="none" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="700" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; min-width: 980px; max-width: 980px; white-space: normal; font-size: 64px; line-height: 74px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Montserrat;text-align:center;background-color:rgba(240, 99, 76, 1.00);">BEST SHOP YOU EVER SEEN </div>

                <!-- LAYER NR. 2 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-24-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['78','78','78','68']" data-width="['631','631','631','440']" data-height="31" data-whitespace="normal" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="800" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; min-width: 631px; max-width: 631px; max-width: 31px; max-width: 31px; white-space: normal; font-size: 20px; line-height: 30px; font-weight: 300; color: rgba(153, 153, 153, 1.00);font-family:Open Sans;text-align:center;text-transform:uppercase;">We Create Awesome and Powerful Websites For Business! </div>

                <!-- LAYER NR. 3 -->
                <div class="tp-caption rev-btn tp-layer-selectable  tp-resizeme" id="slide-24-layer-4" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','middle']" data-voffset="['443','443','443','150']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:0;e:Linear.easeNone;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(51, 51, 51, 1.00);bc:rgba(51, 51, 51, 1.00);-webkit-transition:all 300ms ease;-ms-transition:all 300ms ease;transition:all 300ms ease;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-start="900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: rgba(68, 68, 68, 1.00);font-family:Montserrat;text-transform:uppercase;padding:15px 45px 15px 45px;border-color:rgba(146, 146, 146, 1.00);border-style:solid;border-width:3px;outline:none;box-shadow:3px 3px 0px rgba(0,0,0,0.2);box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">SHOPPING NOW </div>

                <!-- LAYER NR. 4 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-24-layer-13" data-x="['center','center','center','center']" data-hoffset="['-71','-71','-71','-71']" data-y="['middle','middle','middle','middle']" data-voffset="['-93','-93','-93','-93']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="opacity:0;s:300;" data-start="1100" data-responsive_offset="on" style="z-index: 8;"><img src="{{ asset('front/monsterat/upload/star_v1.png') }}" alt="" width="25" height="24" data-ww="['25px','25px','25px','25px']" data-hh="['24px','24px','24px','24px']" data-no-retina> </div>

                <!-- LAYER NR. 5 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-24-layer-12" data-x="['center','center','center','center']" data-hoffset="['-40','-40','-40','-40']" data-y="['middle','middle','middle','middle']" data-voffset="['-92','-92','-92','-92']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="opacity:0;s:300;" data-start="1200" data-responsive_offset="on" style="z-index: 9;"><img src="{{ asset('front/monsterat/upload/star_v2.png') }}" alt="" width="31" height="30" data-ww="['31px','31px','31px','31px']" data-hh="['30px','30px','30px','30px']" data-no-retina> </div>

                <!-- LAYER NR. 6 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-24-layer-10" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-90','-90','-90','-90']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="opacity:0;s:300;" data-start="1300" data-responsive_offset="on" style="z-index: 10;"><img src="{{ asset('front/monsterat/upload/star_v3.png') }}" alt="" width="47" height="44" data-ww="['47px','47px','47px','47px']" data-hh="['44px','44px','44px','44px']" data-no-retina> </div>

                <!-- LAYER NR. 7 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-24-layer-11" data-x="['center','center','center','center']" data-hoffset="['40','40','40','40']" data-y="['middle','middle','middle','middle']" data-voffset="['-92','-92','-92','-92']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="opacity:0;s:300;" data-start="1400" data-responsive_offset="on" style="z-index: 11;"><img src="{{ asset('front/monsterat/upload/star_v2.png') }}" alt="" width="31" height="30" data-ww="['31px','31px','31px','31px']" data-hh="['30px','30px','30px','30px']" data-no-retina> </div>

                <!-- LAYER NR. 8 -->
                <div class="tp-caption tp-layer-selectable  tp-resizeme" id="slide-24-layer-14" data-x="['center','center','center','center']" data-hoffset="['70','70','70','70']" data-y="['middle','middle','middle','middle']" data-voffset="['-93','-93','-93','-93']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:50px;opacity:0;s:300;e:Power3.easeOut;" data-transform_out="opacity:0;s:300;" data-start="1500" data-responsive_offset="on" style="z-index: 12;"><img src="{{ asset('front/monsterat/upload/star_v1.png') }}" alt="" width="25" height="24" data-ww="['25px','25px','25px','25px']" data-hh="['24px','24px','24px','24px']" data-no-retina> </div>
            </li>
        </ul>

        <div class="tp-bannertimer" style="height: 5px; background-color: rgba(255, 255, 255, 0.15);"></div>
    </div>

</div>
